import type { NextPage } from 'next';
import Head from 'next/head';
import Chips from '../components/chips';
import MealsList from '../components/mealsList';

interface HomeProps {
  meals: Array<Meal>;
}

const Home: NextPage<HomeProps> = ({ meals }) => {
  return (
    <>
      <Head>
        <title>Liberet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex flex-col items-center py-2 overflow-scroll"
        style={{ backgroundColor: '#f1f1f1' }}
      >
        <Chips />
        <MealsList meals={meals} />
      </main>
    </>
  );
};

export const getServerSideProps = async () => {
  const res = await fetch(
    'https://www.themealdb.com/api/json/v1/1/filter.php?c=Beef'
  );
  const data = await res.json();

  const meals = data.meals;

  return {
    props: { meals },
  };
};

export default Home;
