import { NextPage } from 'next';
import Head from 'next/head';

const Profile: NextPage = () => {
  return (
    <>
      <Head>
        <title>Liberet - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex flex-col h-screen items-center py-2 overflow-scroll"
        style={{ backgroundColor: '#f1f1f1' }}
      >
        <h1>Profile Page</h1>
      </main>
    </>
  );
};

export default Profile;
